coding_questions = [
    "Reverse a string.",
    "Check if a string is a palindrome.",
    "Find the first non-repeated character in a string.",
    "Implement a function to check if a string has all unique characters.",
    "Count the number of vowels in a string.",
    "Implement a function to remove duplicates from a list.",
    "Check if two strings are anagrams of each other.",
    "Implement a function to find the factorial of a number.",
    "Calculate the nth Fibonacci number.",
    "Write a function to check if a number is prime.",
    "Implement a function to find the intersection of two lists.",
    "Rotate an array to the right by k steps.",
    "Implement a stack using arrays/lists.",
    "Implement a queue using arrays/lists.",
    "Implement a binary search algorithm.",
    "Implement a bubble sort algorithm.",
    "Implement a merge sort algorithm.",
    "Implement a linked list.",
    "Find the largest element in an array.",
    "Calculate the square root of a number without using library functions.",
    "Implement a binary tree and perform an inorder traversal.",
    "Check if a binary tree is balanced.",
    "Write a function to reverse a linked list.",
    "Determine if a linked list has a cycle.",
    "Implement a hash table.",
    "Implement a depth-first search (DFS) algorithm.",
    "Implement a breadth-first search (BFS) algorithm.",
    "Find the missing number in an array of 1 to n.",
    "Determine if a string has balanced parentheses.",
    "Implement a priority queue.",
    "Implement a basic calculator for addition, subtraction, multiplication, and division.",
    "Implement a simple cache.",
    "Find the longest common prefix in an array of strings.",
    "Determine if a number is a power of two.",
    "Implement a binary search in a rotated array.",
    "Count the number of set bits in a binary representation of a number.",
    "Reverse words in a given string.",
    "Implement an algorithm to solve the Tower of Hanoi problem.",
    "Check if a given graph is a tree.",
    "Find the shortest path in a weighted graph using Dijkstra's algorithm.",
    "Check if a string contains only digits.",
    "Implement a function to convert a Roman numeral to an integer.",
    "Find the majority element in an array.",
    "Implement an LRU (Least Recently Used) cache.",
    "Determine if a Sudoku is valid.",
    "Implement a Trie data structure.",
    "Find the longest increasing subsequence in an array.",
    "Implement an algorithm to reverse a sentence word by word.",
    "Implement a function to calculate the power set of a set.",
    "Determine if a string is a valid IP address.",
    "Implement an algorithm to find the shortest common supersequence.",
    "Implement an algorithm to find the shortest path in a maze.",
    "Implement a function to perform string matching using regular expressions.",
    "Write a function to generate all possible valid IP addresses from a given string.",
    "Implement a binary search tree and perform operations like insertion, deletion, and searching.",
    "Check if a given graph is connected.",
    "Implement an algorithm to find the kth smallest/largest element in an array.",
    "Determine if a string is a valid parenthesis expression.",
    "Implement a function to find the longest common substring between two strings.",
    "Implement an algorithm to find the longest palindrome substring in a string.",
    "Check if a tree is a subtree of another tree.",
    "Determine the height of a binary tree.",
    "Implement an algorithm to find the shortest path in a grid with obstacles.",
    "Determine if a number is a palindrome in binary representation.",
    "Implement a function to perform matrix multiplication.",
    "Check if a tree is a binary search tree.",
    "Implement a function to check if a linked list is a palindrome.",
    "Determine if a given sequence of moves is circular in a 2D plane.",
    "Implement an algorithm to find the maximum subarray sum.",
    "Determine if a graph is cyclic.",
    "Implement an algorithm to find the shortest path in a graph using Bellman-Ford algorithm.",
    "Implement an algorithm to find the longest increasing subarray.",
    "Determine if a given tree is a subtree of another tree.",
    "Implement an algorithm to find the articulation points in a graph.",
    "Check if a linked list has a loop and find the start of the loop.",
    "Implement an algorithm to find the minimum spanning tree of a graph using Kruskal's algorithm.",
    "Implement an algorithm to find the diameter of a binary tree.",
    "Determine if a string has balanced square brackets.",
    "Implement an algorithm to find the shortest path in a weighted graph using the Floyd-Warshall algorithm.",
    "Write a function to generate all possible permutations of a string.",
    "Implement an algorithm to find the median of two sorted arrays.",
    "Check if a graph is bipartite.",
    "Implement an algorithm to find the maximum flow in a flow network using the Ford-Fulkerson method.",
    "Determine if a given tree is a balanced binary search tree.",
    "Implement an algorithm to find the longest palindromic subsequence.",
    "Check if a given number is a happy number.",
    "Implement an algorithm to find the topological order of a directed acyclic graph.",
    "Determine if a string is a valid number (integer or floating-point).",
    "Implement an algorithm to find the longest common subsequence of two strings.",
    "Check if a linked list is a circular linked list.",
    "Implement an algorithm to find the longest subarray with at most two distinct elements.",
    "Determine if a given graph is a strongly connected graph.",
    "Implement an algorithm to find the longest subarray with equal number of 0s and 1s.",
    "Check if a given Sudoku puzzle has a solution.",
    "Implement an algorithm to find the longest subarray with sum at most K.",
    "Determine if a binary tree is a subtree of another binary tree.",
    "Implement an algorithm to find the maximum sum rectangle in a 2D matrix.",
    "Check if a given binary tree is a complete binary tree.",
    "Implement an algorithm to find the maximum sum subarray with non-adjacent elements.",
    "Determine if a given string is a valid shuffle of two other strings."
]


